/* Local learning state and quiz rules; no accounts or remote services. */
(function(){'use strict';
const D=window.BIOVISION_DATA,KEY='biovision-energetics-v1',day=86400000,questionById=Object.fromEntries(D.questions.map(q=>[q.id,q]));
const fresh=()=>({version:1,profile:{name:'Learner'},completed:[],visited:[],notes:{},bookmarks:[],tags:{},attempts:{},history:[],discussions:[],session:null});
let state=fresh(),storageAvailable=true;
function validate(raw){if(!raw||raw.version!==1||typeof raw!=='object')throw Error('Choose a BioVision progress backup (version 1).');const out=fresh(),ids=new Set(D.lessons.map(l=>l.id));out.profile.name=String(raw.profile?.name||'Learner').slice(0,60);for(const field of ['completed','visited','bookmarks'])out[field]=Array.isArray(raw[field])?[...new Set(raw[field].filter(id=>ids.has(id)))]:[];
 for(const [id,note] of Object.entries(raw.notes||{}))if(ids.has(id)&&typeof note==='string')out.notes[id]=note.slice(0,20000);
 for(const [id,tags] of Object.entries(raw.tags||{}))if(ids.has(id)&&Array.isArray(tags))out.tags[id]=tags.filter(t=>typeof t==='string').map(t=>t.slice(0,40)).slice(0,10);
 for(const [id,r] of Object.entries(raw.attempts||{}))if(questionById[id]&&r&&Number.isFinite(r.seen)&&Number.isFinite(r.correct))out.attempts[id]={seen:Math.max(0,Math.floor(r.seen)),correct:Math.max(0,Math.min(Math.floor(r.correct),Math.floor(r.seen))),streak:Math.max(0,Number(r.streak)||0),due:Number(r.due)||0,lastWrong:!!r.lastWrong,lastChoice:Number.isInteger(r.lastChoice)?r.lastChoice:null};
 out.history=(Array.isArray(raw.history)?raw.history:[]).filter(h=>h&&Number.isFinite(h.correct)&&Number.isFinite(h.total)&&typeof h.date==='string').slice(-100).map(h=>({id:String(h.id||''),date:h.date,correct:h.correct,total:h.total,mode:String(h.mode||'practice')}));
 out.discussions=(Array.isArray(raw.discussions)?raw.discussions:[]).filter(p=>p&&typeof p.text==='string').slice(-100).map(p=>({id:String(p.id||''),text:p.text.slice(0,5000),lesson:ids.has(p.lesson)?p.lesson:'energy',date:String(p.date||'')}));
 if(raw.session&&!raw.session.done){const s=raw.session,scopes=new Set(['all','respiration','photosynthesis',...ids]);
  if(['practice','adaptive'].includes(s.mode)&&scopes.has(s.scope)&&['mixed','1','2','3'].includes(String(s.level))&&Array.isArray(s.queue)&&s.queue.length>0&&new Set(s.queue).size===s.queue.length&&s.queue.every(id=>questionById[id]&&pool(s.scope).some(q=>q.id===id))&&s.answers&&typeof s.answers==='object'&&Number.isInteger(s.index)&&s.index>=0&&s.index<s.queue.length&&Number.isInteger(s.targetCount)&&s.targetCount>=s.queue.length&&s.targetCount<=pool(s.scope).length&&s.index<s.targetCount){
   const clean=Object.fromEntries(Object.entries(s.answers).filter(([id,r])=>s.queue.includes(id)&&r&&Number.isInteger(r.choice)&&r.choice>=0&&r.choice<questionById[id].options.length).map(([id,r])=>[id,{choice:r.choice,correct:r.choice===questionById[id].answer}]));
   out.session={id:String(s.id||Date.now()).slice(0,60),mode:s.mode,scope:s.scope,level:String(s.level),queue:[...s.queue],index:s.index,targetCount:s.targetCount,answers:clean,currentLevel:Math.max(1,Math.min(3,Math.floor(Number(s.currentLevel)||1))),rightStreak:Math.max(0,Math.min(1,Number(s.rightStreak)||0)),startedAt:Number(s.startedAt)||Date.now(),deadline:Number.isFinite(s.deadline)&&s.deadline>0?s.deadline:null,done:false};
  }
 }
 return out;
}
try{const raw=localStorage.getItem(KEY);if(raw){try{state=validate(JSON.parse(raw));}catch{state=fresh();}}}catch{storageAvailable=false;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageAvailable=true;}catch{storageAvailable=false;}return storageAvailable;}
function record(q,choice){const correct=choice===q.answer,old=state.attempts[q.id]||{seen:0,correct:0,streak:0};old.seen++;old.correct+=correct?1:0;old.streak=correct?old.streak+1:0;old.lastWrong=!correct;old.lastChoice=choice;old.due=Date.now()+(correct?[1,3,7,14,30][Math.min(old.streak-1,4)]*day:0);state.attempts[q.id]=old;save();return correct;}
function pool(scope){return D.questions.filter(q=>scope==='all'||(scope==='respiration'?D.lessons.find(l=>l.id===q.lesson).chapter===9:scope==='photosynthesis'?D.lessons.find(l=>l.id===q.lesson).chapter===10:q.lesson===scope));}
function weakness(lesson){const a=D.questions.filter(q=>q.lesson===lesson).map(q=>state.attempts[q.id]).filter(Boolean);const seen=a.reduce((s,r)=>s+r.seen,0),right=a.reduce((s,r)=>s+r.correct,0);return seen?1-right/seen:.35;}
function pick(s){const remaining=pool(s.scope).filter(q=>!s.queue.includes(q.id));if(!remaining.length)return null;const candidates=remaining.filter(q=>s.mode==='adaptive'?q.level===s.currentLevel:s.level==='mixed'||q.level===Number(s.level));const available=candidates.length?candidates:remaining;return available.map(q=>({q,priority:weakness(q.lesson)+(state.attempts[q.id]?.due<=Date.now() ? .1 : 0)+Math.random()*.12})).sort((a,b)=>b.priority-a.priority)[0].q.id;}
function createSession(settings){const available=pool(settings.scope).filter(q=>settings.mode==='adaptive'||settings.level==='mixed'||q.level===Number(settings.level));if(!available.length)throw Error('No questions match these settings.');const targetCount=Math.min(Math.max(1,Number(settings.count)||5),available.length);const now=Date.now();const s={id:String(now),mode:settings.mode,scope:settings.scope,level:settings.level,currentLevel:settings.level==='mixed'?1:Number(settings.level),rightStreak:0,targetCount,index:0,queue:[],answers:{},startedAt:now,deadline:Number(settings.minutes)>0?now+Number(settings.minutes)*60000:null,done:false};s.queue.push(pick(s));state.session=s;save();return s;}
function answer(choice){if(!Number.isInteger(choice)||choice<0||choice>3)throw Error('Select one of the available answers.');const s=state.session;if(!s||s.done)throw Error('Start a practice session.');if(s.deadline&&Date.now()>=s.deadline){finish();return null;}const id=s.queue[s.index],q=questionById[id];if(s.answers[id])return s.answers[id];const correct=record(q,choice),response={choice,correct};s.answers[id]=response;if(s.mode==='adaptive'){s.rightStreak=correct?s.rightStreak+1:0;if(!correct)s.currentLevel=Math.max(1,s.currentLevel-1);else if(s.rightStreak>=2){s.currentLevel=Math.min(3,s.currentLevel+1);s.rightStreak=0;}}save();return response;}
function next(){const s=state.session;if(!s||!s.answers[s.queue[s.index]])return false;if(s.index+1>=s.targetCount)return finish();s.index++;if(!s.queue[s.index]){const id=pick(s);if(!id)return finish();s.queue.push(id);}save();return true;}
function finish(){const s=state.session;if(!s||s.done)return s;s.done=true;s.finishedAt=Date.now();s.correct=Object.values(s.answers).filter(a=>a.correct).length;state.history.push({id:s.id,date:new Date(s.finishedAt).toISOString(),correct:s.correct,total:s.targetCount,mode:s.mode});state.history=state.history.slice(-100);save();return s;}
function sessionChoices(q,s){const values=q.options.map((text,original)=>({text,original}));let seed=0;for(const c of q.id+s.id)seed=(seed*31+c.charCodeAt(0))>>>0;for(let i=values.length-1;i>0;i--){seed=(1664525*seed+1013904223)>>>0;const j=seed%(i+1);[values[i],values[j]]=[values[j],values[i]];}return values;}
window.BVLearn={data:D,get state(){return state;},get storageAvailable(){return storageAvailable;},questionById,save,record,pool,weakness,createSession,answer,next,finish,sessionChoices,validate,import(raw){state=validate(raw);save();return state;},fresh};
})();
