/* Offline Three.js viewer. Geometry is exported from the accompanying Blender files. */
(function(){
'use strict';
const names={'outer':'Outer membrane / envelope','inner':'Inner membrane / envelope','matrix':'Matrix','stroma':'Stroma','cristae':'Cristae folds','dna':'Organelle DNA','atp-synthase':'ATP synthase','bilayer':'Phospholipid bilayer','protons':'High-concentration protons','complex-i':'Complex I','complex-ii':'Complex II','complex-iii':'Complex III','complex-iv':'Complex IV','q':'Ubiquinone (Q)','cytochrome-c':'Cytochrome c','electron-route':'Electron route','oxygen':'Oxygen acceptor','psii':'Photosystem II','psi':'Photosystem I','pq':'Plastoquinone','b6f':'Cytochrome b6f','pc':'Plastocyanin','fnr':'NADP+ reductase','water':'Water donor','lamella':'Stroma lamellae'};
window.BVViewer={partName:id=>names[id]||id.replace(/-/g,' '),mount(host,modelId,onSelect){
 const data=window.BIOVISION_MODELS[modelId];if(!data||!window.THREE){host.textContent='The 3D model is unavailable. Use the structure descriptions and downloadable Blender files.';return {dispose(){},focus(){},reset(){},setXRay(){},setCutaway(){},setIsolate(){}};}
 const T=window.THREE;let renderer;
 try{renderer=new T.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});}catch{host.textContent='WebGL is unavailable in this browser. Structure descriptions and Blender downloads remain available.';return {dispose(){},focus(){},reset(){},setXRay(){},setCutaway(){},setIsolate(){}};}
 renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.setClearColor(0xeef5f4,1);renderer.localClippingEnabled=true;renderer.outputColorSpace=T.SRGBColorSpace;
 const scene=new T.Scene(),group=new T.Group();scene.add(group);scene.add(new T.HemisphereLight(0xffffff,0x52696a,2.4));const light=new T.DirectionalLight(0xffffff,3.4);light.position.set(8,12,9);scene.add(light);const rim=new T.DirectionalLight(0x96d8ce,1.5);rim.position.set(-9,5,-5);scene.add(rim);
 const camera=new T.PerspectiveCamera(40,1,.05,200),meshes=[];
 for(const part of data.parts){const geom=new T.BufferGeometry();geom.setAttribute('position',new T.Float32BufferAttribute(part.positions,3));geom.setIndex(part.indices);geom.computeVertexNormals();const mat=new T.MeshStandardMaterial({color:new T.Color().setRGB(...part.color.slice(0,3)),roughness:.43,metalness:.08,transparent:part.color[3]<1,opacity:part.color[3],side:T.DoubleSide,depthWrite:part.color[3]>.5});const mesh=new T.Mesh(geom,mat);mesh.userData={...part,baseOpacity:part.color[3]};group.add(mesh);meshes.push(mesh);}
 const bounds=new T.Box3().setFromObject(group),center=bounds.getCenter(new T.Vector3()),size=bounds.getSize(new T.Vector3());for(const mesh of meshes)mesh.geometry.translate(-center.x,-center.y,-center.z);
 const radius=Math.max(size.x,size.y,size.z)/2;let distance=radius*3.5,zoom=1,baseDistance=distance,yaw=.05,pitch=.15,selected=null,xray=false,cutaway=false,isolate=false,disposed=false;
 camera.position.set(distance*.27,distance*.24,distance);camera.lookAt(0,0,0);host.replaceChildren(renderer.domElement);const canvas=renderer.domElement;canvas.tabIndex=0;canvas.setAttribute('aria-label',data.name+'. Drag to rotate; scroll to zoom; use arrow keys to rotate. Select structures from the buttons.');
 const clip=new T.Plane(new T.Vector3(0,0,-1),0);
 function render(){if(disposed)return;group.rotation.set(pitch,yaw,0);camera.position.set(distance*.27,distance*.24,distance);camera.lookAt(0,0,0);renderer.render(scene,camera);}
 function style(){for(const mesh of meshes){const id=mesh.userData.id,shell=['outer','inner','matrix','stroma'].includes(id);mesh.visible=!isolate||!selected||id===selected;mesh.material.opacity=xray&&shell ? .09 : mesh.userData.baseOpacity;mesh.material.transparent=mesh.material.opacity<1;mesh.material.depthWrite=mesh.material.opacity>.5;mesh.material.emissive.setHex(selected===id?0x284b36:0x000000);mesh.material.emissiveIntensity=selected===id ? .55 : 0;mesh.material.clippingPlanes=cutaway&&['outer','inner'].includes(id)?[clip]:[];mesh.material.needsUpdate=true;}render();}
 function resize(){const width=Math.max(100,host.clientWidth),height=Math.max(240,host.clientHeight);renderer.setSize(width,height,false);camera.aspect=width/height;baseDistance=Math.max(size.y,size.x/camera.aspect)/(2*Math.tan(Math.PI/9))*1.2+size.z*.5;distance=baseDistance*zoom;camera.updateProjectionMatrix();render();}
 const abort=new AbortController();let drag=null;const ray=new T.Raycaster(),pointer=new T.Vector2();
 canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY};canvas.setPointerCapture(e.pointerId);},{signal:abort.signal});
 canvas.addEventListener('pointermove',e=>{if(!drag)return;yaw+=(e.clientX-drag.x)*.008;pitch=Math.max(-1.4,Math.min(1.4,pitch+(e.clientY-drag.y)*.008));drag.x=e.clientX;drag.y=e.clientY;render();},{signal:abort.signal});
 canvas.addEventListener('pointerup',e=>{if(drag&&Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)<5){const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(meshes.filter(m=>m.visible&&!['outer','inner','matrix','stroma'].includes(m.userData.id)));if(hit[0])onSelect?.(hit[0].object.userData.id);}drag=null;},{signal:abort.signal});
 canvas.addEventListener('pointercancel',()=>drag=null,{signal:abort.signal});
 canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.55,Math.min(3,zoom*Math.exp(e.deltaY*.001)));distance=baseDistance*zoom;render();},{passive:false,signal:abort.signal});
 canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-'].includes(e.key)){e.preventDefault();if(e.key==='ArrowLeft')yaw-=.12;if(e.key==='ArrowRight')yaw+=.12;if(e.key==='ArrowUp')pitch-=.12;if(e.key==='ArrowDown')pitch+=.12;if(e.key==='+'||e.key==='=')zoom=Math.max(.55,zoom*.9);if(e.key==='-')zoom=Math.min(3,zoom*1.1);distance=baseDistance*zoom;render();}},{signal:abort.signal});
 const observer=new ResizeObserver(resize);observer.observe(host);resize();
 return {focus(id){selected=id;style();},setXRay(v){xray=v;style();},setCutaway(v){cutaway=v;style();},setIsolate(v){isolate=v;style();},reset(){zoom=1;distance=baseDistance;yaw=.05;pitch=.15;selected=null;xray=false;cutaway=false;isolate=false;style();},dispose(){disposed=true;abort.abort();observer.disconnect();for(const m of meshes){m.geometry.dispose();m.material.dispose();}renderer.dispose();renderer.forceContextLoss();}};
}};
})();
