from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
lessons=[];questions=[]
def L(id,title,chapter,minutes,model,summary,where,why,who,how,points,steps,myth,truth,ledger):
 lessons.append(dict(id=id,title=title,chapter=chapter,minutes=minutes,model=model,summary=summary,fiveW={'What':summary,'Where':where,'Why':why,'Who':who,'How':how},points=points,steps=[{'title':a,'text':b,'why':c} for a,b,c in steps],misconception={'myth':myth,'truth':truth},ledger=ledger,source='Campbell Biology, supplied Chapters 9–10; explanations written for this unit.'))
def Q(lesson,level,prompt,options,answer,explanation):
 questions.append(dict(id=f'{lesson}-q{sum(q["lesson"]==lesson for q in questions)+1}',lesson=lesson,level=level,type='mcq',prompt=prompt,options=options,answer=answer,explanation=explanation))
L('energy','Energy, ATP & redox',9,7,'mitochondrion','Cells transfer energy through coupled reactions, and electron carriers connect fuel breakdown with ATP production.','ATP coupling occurs throughout the cell; respiratory pathways span cytosol and mitochondria.','Many cellular tasks are energetically unfavorable on their own. Coupling them to favorable reactions makes a combined process possible.','ATP and ADP; redox enzymes; NAD+/NADH and FAD/FADH2.','Fuel oxidation transfers electrons to carriers. Energy is released in controlled steps and some is captured in ATP.',[
'ATP hydrolysis can be coupled to transport, movement or synthesis; ATP is a transferable energy currency rather than long-term fuel storage.',
'Oxidation means losing electrons; reduction means gaining electrons. These processes occur together in a redox reaction.',
'NAD+ accepts electrons and becomes NADH. NADH later donates electrons and is oxidized back to NAD+.',
'Enzymes lower activation barriers. They do not change the overall free-energy difference or create energy.'],[
('Oxidize fuel','Electrons are transferred from fuel molecules to electron carriers.','Energy is captured gradually rather than released in one uncontrolled reaction.'),('Capture usable energy','ATP and reduced carriers store part of the transferred chemical energy.','Carriers connect reactions occurring at different times and locations.'),('Couple cellular work','ATP hydrolysis is coupled to an otherwise unfavorable cellular process.','Coupling links the energy-releasing and energy-requiring reactions.')],
'Breaking an ATP bond alone releases energy.','Breaking a bond requires energy. ATP hydrolysis is favorable because the complete reaction produces more stable products.',[['ATP cycle','ATP → ADP + Pi','Work is coupled to the full reaction'],['Carrier cycle','NAD+ ↔ NADH','Electron transfer connects pathways']])
Q('energy',1,'Which change is an oxidation?', ['A molecule loses electrons','NAD+ gains electrons','ADP gains a phosphate','A molecule gains electrons'],0,'Oxidation is loss of electrons; reduction is gain. Phosphate transfer alone does not identify a redox event.')
Q('energy',2,'An enzyme speeds a reaction. Which statement remains true?', ['The enzyme makes all reactions spontaneous','The enzyme changes the equilibrium position','The enzyme lowers the activation barrier','The enzyme supplies unlimited energy'],2,'An enzyme lowers the activation barrier. It does not alter the reaction’s overall free-energy change or equilibrium.')
Q('energy',3,'A cell couples an unfavorable synthesis to ATP hydrolysis. What must be true of the combined reaction?', ['Its total free-energy change is favorable under the cell’s conditions','Its synthesis step becomes independent of ATP','ATP becomes the final electron acceptor','Every individual step must release energy'],0,'Coupling can make the sum favorable even when the synthesis alone is unfavorable. Individual steps need not all release energy.')

L('glycolysis','Glycolysis: one glucose, two pyruvates',9,8,'mitochondrion','Glycolysis splits one six-carbon glucose into two three-carbon pyruvates and captures ATP and NADH.','The cytosol, outside the mitochondrial matrix.','It provides an initial way to extract energy from glucose, including when oxygen is unavailable.','Glucose, ATP, ADP, NAD+, enzymes and two three-carbon intermediates.','An investment phase uses two ATP. A payoff phase produces four ATP and two NADH per glucose.',[
'Net yield per glucose: two pyruvates, two ATP and two NADH.',
'ATP is formed by substrate-level phosphorylation: a phosphate is transferred from an intermediate to ADP.',
'Glycolysis does not directly require O2, but it requires a supply of NAD+.',
'Carbon remains in the two pyruvates; glycolysis does not release CO2.'],[
('Invest energy','Two ATP are consumed as glucose is phosphorylated and prepared for splitting.','Phosphorylation helps keep glucose in the cell and prepares it for later reactions.'),('Split and oxidize','The six-carbon pathway becomes two three-carbon pathways; NAD+ is reduced.','Two parallel payoff sequences account for the doubled product numbers.'),('Collect the payoff','Four ATP are formed and two pyruvates remain. Net ATP equals four produced minus two invested.','Net yield accounts for the earlier investment.')],
'Glycolysis makes four net ATP.','It produces four ATP but consumes two, so the net yield is two ATP per glucose.',[['Carbon','1 glucose (6 C) → 2 pyruvates (3 C each)','No CO2 released'],['ATP','2 consumed; 4 produced','Net 2 ATP'],['Carriers','2 NAD+ → 2 NADH','Per glucose']])
Q('glycolysis',1,'Where does glycolysis occur in a eukaryotic cell?', ['Mitochondrial matrix','Cytosol','Thylakoid lumen','Intermembrane space'],1,'Glycolysis occurs in the cytosol. Pyruvate oxidation and most citric acid cycle reactions occur in the mitochondrial matrix.')
Q('glycolysis',2,'Four ATP are produced and two ATP are consumed. What is the net ATP yield per glucose?', ['2','4','6','0'],0,'Net yield subtracts the investment: 4 − 2 = 2 ATP.')
Q('glycolysis',3,'If NAD+ cannot be regenerated, why will glycolysis eventually slow?', ['Glucose cannot enter any cell','Oxygen is a direct glycolytic reactant','The oxidation step lacks its electron acceptor','Pyruvate instantly becomes six-carbon glucose'],2,'A glycolytic oxidation requires NAD+ as an electron acceptor. A finite NAD+ pool must be regenerated, by respiration or fermentation.')

L('pyruvate','Pyruvate oxidation: the bridge',9,6,'mitochondrion','Pyruvate oxidation links glycolysis to the citric acid cycle by producing acetyl-CoA.','In the mitochondrial matrix of eukaryotic cells.','The acetyl group can enter the cycle, while electrons are captured in NADH.','Pyruvate dehydrogenase complex, pyruvate, NAD+ and coenzyme A.','Each three-carbon pyruvate loses one carbon as CO2. Its remaining two-carbon acetyl group attaches to CoA.',[
'Per glucose, two pyruvates produce two acetyl-CoA, two CO2 and two NADH.',
'This bridge reaction does not directly make ATP.',
'Coenzyme A carries the acetyl group; its attachment helps make subsequent transfer energetically useful.',
'The two acetyl carbons enter the citric acid cycle; pyruvate itself does not enter the cycle as the starting input.'],[
('Release one carbon','One carbon from each pyruvate leaves as CO2.','This connects three-carbon pyruvate with the two-carbon acetyl group.'),('Capture electrons','NAD+ is reduced to NADH.','Oxidation energy is transferred to an electron carrier.'),('Attach coenzyme A','The acetyl group is linked to coenzyme A.','Acetyl-CoA transfers its acetyl group into the next pathway.')],
'Pyruvate oxidation directly makes ATP.','It makes NADH and acetyl-CoA but no ATP directly.',[['Per pyruvate','1 acetyl-CoA; 1 CO2; 1 NADH','No direct ATP'],['Per glucose','2 acetyl-CoA; 2 CO2; 2 NADH','Two bridge reactions']])
Q('pyruvate',1,'What is the two-carbon product that enters the citric acid cycle?', ['Acetyl-CoA','Glucose','Oxygen','Lactate'],0,'Acetyl-CoA transfers a two-carbon acetyl group to oxaloacetate at the start of the cycle.')
Q('pyruvate',2,'How much CO2 does pyruvate oxidation release per glucose?', ['0','1','2','6'],2,'Two pyruvates form per glucose. Each loses one carbon as CO2, giving two CO2 in this stage.')
Q('pyruvate',3,'A drug blocks pyruvate dehydrogenase. Which direct consequence is most likely?', ['Less glucose-derived acetyl-CoA enters the cycle','More ATP is produced by the bridge reaction','Water splitting stops','NADP+ becomes the terminal acceptor'],0,'Blocking the bridge reduces conversion of glucose-derived pyruvate to acetyl-CoA. Other fuel sources may still supply acetyl-CoA.')

L('citric','The citric acid cycle',9,8,'mitochondrion','The cycle oxidizes acetyl groups and regenerates oxaloacetate while loading NADH and FADH2.','Most reactions occur in the mitochondrial matrix; succinate dehydrogenase is associated with the inner membrane.','Much of the captured energy is carried onward as reduced electron carriers, rather than direct ATP.','Acetyl-CoA, oxaloacetate, cycle enzymes, NAD+, FAD and ADP/GDP.','Two acetyl carbons join four-carbon oxaloacetate. A series of reactions releases CO2 and restores the four-carbon acceptor.',[
'One turn per acetyl-CoA yields three NADH, one FADH2, one ATP or GTP, and two CO2.',
'Two turns per glucose yield six NADH, two FADH2, two ATP/GTP and four CO2.',
'Oxaloacetate is regenerated; it is not consumed once for every turn.',
'The cycle does not directly consume O2, but carrier recycling normally depends on oxygen-linked respiration.'],[
('Join the cycle','A two-carbon acetyl group combines with four-carbon oxaloacetate.','The six-carbon product begins a cycle that can be repeated.'),('Oxidize and capture','Reactions release CO2 and reduce NAD+ and FAD; substrate-level phosphorylation forms ATP or GTP.','Reduced carriers capture most of the pathway’s usable energy.'),('Regenerate the acceptor','Four-carbon oxaloacetate is restored.','Regeneration allows another acetyl group to enter.')],
'One glucose produces only one turn of the cycle.','One glucose normally supplies two acetyl-CoA, so the cycle turns twice.',[['One turn','3 NADH; 1 FADH2; 1 ATP/GTP; 2 CO2','Per acetyl-CoA'],['Two turns','6 NADH; 2 FADH2; 2 ATP/GTP; 4 CO2','Per glucose']])
Q('citric',1,'Which molecule is regenerated at the end of the citric acid cycle?', ['Glucose','Oxaloacetate','Oxygen','Pyruvate'],1,'Oxaloacetate is the four-carbon acceptor regenerated by the cycle.')
Q('citric',2,'How many NADH are produced by two turns of the cycle?', ['2','3','6','10'],2,'Each turn forms three NADH, so two turns form six. Ten is the total across several glucose-oxidation stages, not the cycle alone.')
Q('citric',3,'Why can oxygen removal slow the cycle even though O2 is not a direct cycle reactant?', ['CO2 replaces oxygen in ATP synthase','The cycle requires light','Carrier recycling through the respiratory chain becomes limited','Oxaloacetate becomes a photon'],2,'Without the respiratory terminal acceptor, NADH oxidation is impaired. NAD+ becomes less available for further cycle reactions.')

L('etc','Electron transport: donor to oxygen',9,10,'respiratory-etc','The respiratory electron transport chain transfers electrons to oxygen and uses released energy to build a proton gradient.','The mitochondrial inner membrane; protons are moved from the matrix into the intermembrane space.','Controlled electron transfer stores energy as an electrochemical gradient that ATP synthase can use.','NADH, FAD-linked electrons, complexes I–IV, ubiquinone, cytochrome c and O2.','NADH donates to complex I. Electrons from succinate enter via complex II and Q. Q → III → cytochrome c → IV transfers electrons to O2.',[
'Complexes I, III and IV contribute to proton pumping; complex II does not pump protons.',
'Ubiquinone (Q) moves within the membrane; cytochrome c moves on the intermembrane-space side.',
'Oxygen accepts electrons at the end of the chain and is reduced to water.',
'Electron transport establishes the gradient; ATP synthase is a separate complex that uses the gradient.',
'The uploaded clips are brief visual demonstrations. They are accompanied here by complete explanatory text.'],[
('Donate electrons','NADH is oxidized at complex I. FAD-linked electrons can enter through complex II toward Q.','Entry points matter: bypassing complex I reduces the proton translocation associated with those electrons.'),('Transfer and pump','Q and cytochrome c connect large complexes. Transfer energy supports proton movement into the intermembrane space.','This separates proton concentration and charge across an intact membrane.'),('Reduce oxygen','Complex IV transfers electrons to O2, forming water.','A terminal acceptor permits continuing electron flow and carrier regeneration.'),('Connect to ATP synthesis','Protons can return to the matrix through ATP synthase.','The gradient, rather than a direct electron-to-ATP transfer, powers ATP synthesis.')],
'Complex II pumps protons just like complex I.','Complex II passes electrons toward Q but does not pump protons across the inner membrane.',[['Electron donors','NADH; FAD-linked electrons','Different chain entry points'],['Terminal acceptor','O2 → H2O','At complex IV'],['Proton movement','Matrix → intermembrane space','By the chain; return through ATP synthase']])
Q('etc',1,'Which respiratory complex does not pump protons?', ['Complex I','Complex II','Complex III','Complex IV'],1,'Complex II transfers electrons to Q but does not pump protons. I, III and IV contribute to proton translocation.')
Q('etc',2,'Where do pumped protons accumulate in mitochondria?', ['Cytosol only','Matrix','Intermembrane space','Thylakoid stroma'],2,'The respiratory chain moves protons from the matrix to the intermembrane space.')
Q('etc',3,'A compound blocks complex IV. Which immediate change is expected?', ['Oxygen reduction and upstream electron flow decline','Glycolysis directly starts consuming O2','Complex II begins pumping protons','ATP synthase makes its own electron supply'],0,'Complex IV performs the terminal transfer to oxygen. A block restricts oxygen reduction and backs up electron flow upstream.')

L('chemiosmosis','Chemiosmosis & ATP synthase',9,8,'respiratory-etc','Proton flow through ATP synthase couples an electrochemical gradient to ATP production.','Across the mitochondrial inner membrane; the catalytic ATP synthase head faces the matrix.','A membrane gradient lets many electron-transfer steps power a shared ATP-producing mechanism.','ATP synthase, H+, ADP and inorganic phosphate (Pi).','The respiratory chain establishes the gradient. H+ returns down its electrochemical gradient through ATP synthase; conformational changes drive ATP formation.',[
'The proton-motive force includes both a concentration difference and an electrical potential difference.',
'A sufficiently intact membrane is essential; a proton leak dissipates the gradient.',
'Oxidative phosphorylation combines electron transport with chemiosmosis. It differs from substrate-level phosphorylation.',
'Aerobic glucose oxidation in eukaryotic cells often yields about 30–32 ATP; yield is not a single fixed number across all conditions.'],[
('Build the gradient','Electron transport moves H+ against its electrochemical gradient.','Input energy is required to maintain a difference across the membrane.'),('Let protons return','H+ moves through ATP synthase toward the matrix.','Controlled return captures energy that would otherwise dissipate.'),('Make ATP','ADP and Pi form ATP through the enzyme’s coupled conformational changes.','The catalytic head converts the stored gradient energy into transferable chemical energy.')],
'Electrons flow through ATP synthase to make ATP.','Protons flow through ATP synthase. Electrons pass through the electron transport chain.',[['Chain','Electron transfer → proton gradient','Energy transfer'],['ATP synthase','ADP + Pi → ATP','Coupled to proton return'],['Uncoupling','Proton leak reduces ATP coupling','O2 consumption and ATP output can diverge']])
Q('chemiosmosis',1,'What passes through ATP synthase to power ATP synthesis?', ['Electrons','CO2','Protons','Glucose'],2,'H+ flows down its electrochemical gradient through ATP synthase. Electrons move through separate chain components.')
Q('chemiosmosis',2,'A protonophore makes the inner membrane leaky to H+. Which result is expected?', ['ATP production becomes more tightly coupled','The gradient and coupled ATP output decrease','The citric acid cycle becomes photosynthesis','All proton movement stops'],1,'A proton leak dissipates the gradient, reducing ATP synthesis coupled to respiration. Electron transport may continue or increase under suitable conditions.')
Q('chemiosmosis',3,'O2 consumption continues but ATP production falls after a treatment. Which mechanism best fits?', ['An uncoupler allows protons to bypass ATP synthase','All glucose carbon becomes oxygen','NADH can no longer donate any electrons','ATP synthase replaces complex IV'],0,'Uncoupling can permit respiration while reducing ATP output because the proton gradient is dissipated without productive ATP synthesis.')

L('fermentation','Fermentation & NAD+ recycling',9,7,'mitochondrion','Fermentation regenerates NAD+ so glycolysis can continue when respiratory NADH oxidation is unavailable.','The cytosol.','A finite NAD+ supply must be restored for continued glycolytic oxidation.','NADH, pyruvate or a pyruvate-derived product, and fermentation enzymes.','In lactate fermentation, pyruvate accepts electrons from NADH. In alcohol fermentation, pyruvate loses CO2 and acetaldehyde accepts electrons.',[
'Fermentation’s essential role is NAD+ regeneration; it makes no additional ATP beyond glycolysis in these pathways.',
'The net ATP yield associated with glycolysis plus lactate/alcohol fermentation is two ATP per glucose.',
'Lactate fermentation does not release CO2 in its pyruvate-to-lactate step; alcohol fermentation does.',
'Anaerobic respiration uses an electron transport chain with a terminal acceptor other than O2; it is different from fermentation.'],[
('Produce pyruvate and NADH','Glycolysis supplies both while making net two ATP.','Glycolysis depends on recycled NAD+.'),('Transfer electrons to an organic acceptor','NADH reduces pyruvate or acetaldehyde.','Reduction oxidizes NADH back to NAD+.'),('Recycle NAD+','NAD+ returns to glycolysis.','Regeneration sustains glycolytic ATP production without the aerobic respiratory chain.')],
'Fermentation adds a large ATP payoff after glycolysis.','The fermentation steps recycle NAD+; the two net ATP come from glycolysis.',[['Lactate route','Pyruvate + NADH → lactate + NAD+','No CO2 in this conversion'],['Alcohol route','Pyruvate → acetaldehyde + CO2; then ethanol','NAD+ regenerated'],['Net ATP','2 per glucose','Produced by glycolysis']])
Q('fermentation',1,'What is the main role of fermentation?', ['Make oxygen','Regenerate NAD+','Pump mitochondrial protons','Fix atmospheric CO2'],1,'Fermentation oxidizes NADH to regenerate NAD+, allowing glycolysis to continue.')
Q('fermentation',2,'What is the net ATP yield from glycolysis plus lactate fermentation per glucose?', ['0','2','4','32'],1,'The net two ATP are made in glycolysis; lactate fermentation does not add ATP.')
Q('fermentation',3,'Which finding distinguishes anaerobic respiration from fermentation?', ['Use of an electron transport chain and a non-O2 terminal acceptor','Both always release oxygen','Absence of electron transfers','Use of the Calvin cycle'],0,'Anaerobic respiration uses a chain and an alternative terminal acceptor. Fermentation regenerates carriers by reducing organic molecules without a respiratory chain.')

L('fuels','Other fuels & pathway regulation',9,6,'mitochondrion','Respiratory pathways accept several fuel types and respond to the cell’s energy needs.','Entry points span glycolysis, acetyl-CoA formation and the citric acid cycle.','Cells must coordinate energy extraction with fuel availability and biosynthesis.','Carbohydrates, fatty acids, amino acids and regulatory enzymes.','Glycerol can enter glycolysis; fatty acids undergo beta-oxidation to acetyl-CoA; deaminated amino-acid carbon skeletons enter at various points.',[
'Proteins generally require removal of amino groups before their carbon skeletons enter energy pathways.',
'Fats can supply substantial chemical energy because many of their carbons are highly reduced.',
'High ATP availability can inhibit key catabolic control steps; AMP/ADP can signal greater ATP demand.',
'Pathway intermediates also support biosynthesis, so respiration is connected to many other cellular processes.'],[
('Prepare the fuel','Break larger nutrients into molecules that can enter shared pathways.','Different nutrients require different initial processing.'),('Join a shared pathway','Carbon skeletons enter glycolysis, acetyl-CoA production or the cycle.','Shared downstream steps allow flexible fuel use.'),('Adjust the rate','Regulatory signals alter enzyme activity as energy demand changes.','Feedback helps avoid unnecessary breakdown when ATP is abundant.')],
'Every respiratory fuel must first become glucose.','Several fuels enter downstream of glucose, including fatty-acid-derived acetyl-CoA.',[['Fatty acids','Beta-oxidation → acetyl-CoA','Not necessarily glucose first'],['Amino acids','Deamination then pathway entry','Entry depends on the carbon skeleton']])
Q('fuels',1,'Which product of fatty acid beta-oxidation enters the citric acid cycle?', ['Acetyl-CoA','Chlorophyll','O2','RuBP'],0,'Beta-oxidation generates acetyl-CoA units that can enter the cycle.')
Q('fuels',2,'Why must many amino acids be deaminated before use as fuel?', ['Their amino groups must be removed before carbon-skeleton processing','All amino acids are six-carbon sugars','Nitrogen pumps protons directly','Deamination produces photons'],0,'Removing amino groups prepares carbon skeletons for entry into metabolic pathways.')
Q('fuels',3,'A cell has abundant ATP and low energy demand. Which response is consistent with feedback control?', ['Inhibition of some catabolic control enzymes','Unlimited acceleration of all glycolysis','Automatic conversion of all proteins to ATP','Activation of water splitting in mitochondria'],0,'ATP can signal energy sufficiency and inhibit some regulatory steps, coordinating fuel breakdown with demand.')

L('chloroplast','Chloroplast compartments',10,7,'chloroplast','Chloroplasts separate light reactions in thylakoid membranes from carbon fixation in the stroma.','Photosynthetic cells, especially leaf mesophyll cells in plants.','Compartments organize reactions and allow a thylakoid proton gradient to form.','Envelope membranes, stroma, thylakoid membranes, lumen, grana and lamellae.','Light-reaction proteins occupy thylakoid membranes. ATP and NADPH produced on the stromal side support the Calvin cycle in the stroma.',[
'The envelope surrounds the organelle; it is different from the internal thylakoid membrane.',
'A granum is a stack of thylakoids. The lumen is the space inside a thylakoid.',
'The stroma is outside the thylakoid lumen and inside the inner envelope.',
'Plants also carry out cellular respiration. Photosynthesis does not eliminate their need for mitochondria.'],[
('Locate the envelope','Find the double boundary around the chloroplast.','It defines the organelle’s compartment.'),('Locate grana and lumen','Inspect the stacks of thylakoid discs and their internal spaces.','Membrane and lumen are distinct structures with different roles.'),('Locate the stroma','Identify the fluid region surrounding the thylakoids.','This is where the Calvin cycle uses ATP and NADPH.')],
'The Calvin cycle takes place inside the thylakoid lumen.','It takes place in the stroma; the lumen participates in the proton gradient.',[['Thylakoid membrane','Light reactions','Contains photosystems and carriers'],['Lumen','H+ accumulation','Inside thylakoids'],['Stroma','Calvin cycle','Outside thylakoid lumen']])
Q('chloroplast',1,'Where does the Calvin cycle occur?', ['Thylakoid lumen','Stroma','Mitochondrial matrix','Cytosol only'],1,'The Calvin cycle occurs in the stroma, whereas light-reaction proteins occupy thylakoid membranes.')
Q('chloroplast',2,'What is a granum?', ['A stack of thylakoids','A molecule of glucose','The outer envelope','An ATP synthase electron'],0,'A granum is a thylakoid stack. Its membrane surrounds internal lumen spaces.')
Q('chloroplast',3,'Which statement about green plant cells is correct?', ['They can use both chloroplast photosynthesis and mitochondrial respiration','They never use oxygen','Their mitochondria are replaced by chloroplasts','They only make ATP at night'],0,'Photosynthetic plant cells can carry out both photosynthesis and cellular respiration.')

L('pigments','Light, pigments & photosystems',10,7,'light-reactions','Pigments absorb selected wavelengths, and photosystems organize light capture and electron transfer.','Pigments are associated with photosystem proteins in thylakoid membranes.','Light energy must be captured and converted into useful chemical processes.','Chlorophyll a, chlorophyll b, accessory pigments, antenna complexes and reaction-center chlorophyll.','Antenna pigments transfer excitation energy toward a reaction center, where an excited electron is transferred to an acceptor.',[
'Absorption spectra measure which wavelengths a pigment absorbs; action spectra measure the biological response to wavelengths.',
'Accessory pigments broaden light capture and can help protect against excess light.',
'Energy transfer between antenna pigments is not the same as the reaction center’s electron transfer.',
'Photosystem II operates before photosystem I in linear electron flow; numbering reflects discovery, not pathway order.'],[
('Absorb a photon','A pigment absorbs light of a suitable wavelength.','Only absorbed energy can contribute to excitation.'),('Transfer excitation','Antenna complexes funnel excitation toward the reaction center.','Many pigments can support a common reaction-center event.'),('Transfer an electron','Reaction-center chlorophyll transfers an excited electron to an acceptor.','Electron transfer converts a brief excited state into a useful chemical event.')],
'Photosystem I always comes first because it is numbered I.','Linear electron flow begins at photosystem II and then reaches photosystem I.',[['Absorption spectrum','Pigment light absorption','Physical measurement'],['Action spectrum','Photosynthetic response to wavelength','Biological measurement']])
Q('pigments',1,'Which photosystem operates first in linear electron flow?', ['Photosystem I','Photosystem II','ATP synthase','The Calvin photosystem'],1,'Linear flow starts at photosystem II, then reaches photosystem I. The names reflect discovery order.')
Q('pigments',2,'What does an action spectrum measure?', ['A biological response at different wavelengths','Only one pigment’s absorption','The number of CO2 molecules in one ATP','Membrane thickness'],0,'An action spectrum measures biological effectiveness, such as photosynthetic activity, across wavelengths.')
Q('pigments',3,'Why is excitation transfer in an antenna different from reaction-center electron transfer?', ['Excitation transfers energy; the reaction center transfers an electron to an acceptor','Both are always identical electron movements','Antenna pigments perform the Calvin cycle','The reaction center only reflects light'],0,'Antenna pigments funnel excitation energy, while a reaction center performs charge separation by transferring an electron.')

L('light','Light reactions: ATP, NADPH & oxygen',10,10,'light-reactions','Linear electron flow uses light and water to support ATP and NADPH production while releasing oxygen.','The thylakoid membrane; H+ accumulates in the lumen and returns toward the stroma through ATP synthase.','ATP provides energy and NADPH provides reducing power for carbon fixation.','PSII, water, plastoquinone, cytochrome b6f, plastocyanin, PSI, ferredoxin, NADP+ reductase and ATP synthase.','Light excites electrons twice. Water replaces electrons lost from PSII. Electrons ultimately reduce NADP+; proton accumulation drives photophosphorylation.',[
'Released O2 comes from water oxidation, not from CO2.',
'PSII → carrier chain → PSI → ferredoxin → NADP+ reduction describes linear electron flow.',
'ATP synthase releases ATP on the stromal side; NADPH is also available to stromal reactions.',
'Cyclic electron flow around PSI can help generate extra ATP without producing NADPH or O2 through that cyclic route.'],[
('Replace PSII electrons','Water oxidation supplies electrons, releases O2 and adds protons to the lumen.','Electron donation permits continuing PSII activity.'),('Transfer electrons and build a gradient','Carriers connect PSII with PSI while proton accumulation increases.','The gradient supports ATP production across the thylakoid membrane.'),('Re-excite and reduce NADP+','Light at PSI raises electron energy again; electrons ultimately reduce NADP+.','NADPH supplies reducing power needed for carbon fixation.'),('Make ATP','H+ returns toward the stroma through ATP synthase.','Photophosphorylation captures gradient energy as ATP.')],
'The oxygen released by photosynthesis comes from CO2.','Released molecular oxygen comes from water oxidized at photosystem II.',[['Inputs','Light; H2O; NADP+; ADP + Pi','Linear flow'],['Outputs','O2; NADPH; ATP','For exchange and stromal metabolism'],['H+ route','Lumen → stroma through ATP synthase','Return direction']])
Q('light',1,'Where does the O2 released by photosynthesis come from?', ['CO2','ATP','Water','Glucose'],2,'Water oxidation at PSII supplies electrons and releases oxygen.')
Q('light',2,'Which pair links the light reactions to the Calvin cycle?', ['ATP and NADPH','O2 and FADH2','Lactate and ethanol','Pyruvate and oxygen'],0,'ATP provides energy and NADPH provides reducing power for Calvin-cycle reactions.')
Q('light',3,'A chloroplast needs additional ATP relative to NADPH. Which pathway can help?', ['Cyclic electron flow around PSI','Lactate fermentation in the lumen','Blocking all light absorption','Releasing glucose directly from PSII'],0,'Cyclic electron flow around PSI supports additional proton-gradient-driven ATP production without net NADPH production through that route.')

L('calvin','The Calvin cycle: fixation to G3P',10,9,'chloroplast','The Calvin cycle incorporates CO2 into organic molecules using ATP and NADPH.','The chloroplast stroma.','Carbon fixation builds organic carbon that can support sugars and other biosynthesis.','Rubisco, RuBP, 3-PGA, G3P, ATP and NADPH.','CO2 is fixed to RuBP, intermediates are reduced to G3P, and most G3P-derived carbon regenerates RuBP.',[
'Three CO2 entering the cycle support one net G3P output and consume nine ATP and six NADPH.',
'The other five of the six generated G3P molecules are used to regenerate three RuBP molecules.',
'One G3P has three carbons; glucose has six. Glucose is not the cycle’s immediate net product.',
'Light-independent means photons are not direct reactants; it does not mean the cycle normally operates only at night.'],[
('Fix carbon','Rubisco catalyzes addition of CO2 to RuBP, producing 3-PGA after the unstable intermediate splits.','Inorganic carbon becomes part of organic molecules.'),('Reduce intermediates','ATP and NADPH support conversion of 3-PGA toward G3P.','The carbon products receive energy and reducing power.'),('Regenerate RuBP','Most G3P carbon is rearranged, with ATP input, to restore RuBP.','Regeneration allows continued CO2 fixation.')],
'The Calvin cycle directly produces one glucose after each turn.','Its net exported product is G3P; three CO2 give one net G3P, and further reactions can build sugars.',[['For 3 CO2','9 ATP + 6 NADPH consumed','1 net G3P'],['Carbon bookkeeping','6 G3P formed; 1 exits; 5 support regeneration','Three RuBP restored']])
Q('calvin',1,'What is the net exported three-carbon product of the Calvin cycle?', ['G3P','Oxygen','Acetyl-CoA','NADH'],0,'G3P is the immediate net carbon product. It can later contribute to sugar synthesis.')
Q('calvin',2,'How many ATP and NADPH are needed for one net G3P from three CO2?', ['3 ATP and 2 NADPH','9 ATP and 6 NADPH','6 ATP and 9 NADPH','No ATP or NADPH'],1,'Carbon fixation, reduction and RuBP regeneration together require nine ATP and six NADPH for one net G3P.')
Q('calvin',3,'Why would carbon fixation decline after prolonged darkness even though photons are not direct Calvin-cycle reactants?', ['ATP/NADPH supply and light-linked regulation change','The cycle’s only substrate is a photon','CO2 must first become oxygen','Rubisco becomes a mitochondrial carrier'],0,'The cycle depends on energy and reducing power normally supplied by light reactions, as well as light-linked regulation.')

L('photorespiration','Photorespiration: competing substrates',10,7,'chloroplast','Rubisco can act with O2 instead of CO2, initiating photorespiration and reducing productive carbon fixation.','The pathway spans chloroplasts, peroxisomes and mitochondria.','Rubisco’s competing activities help explain why hot, dry conditions can lower photosynthetic efficiency.','Rubisco, RuBP, CO2, O2 and enzymes that recover part of the resulting carbon.','Stomatal closure conserves water but can lower internal CO2. Oxygenation of RuBP becomes more competitive, and recovery costs energy while releasing some CO2.',[
'Photorespiration differs from mitochondrial respiration and does not provide a comparable ATP payoff.',
'Rubisco’s oxygenase activity competes with its carboxylase activity.',
'Hot, dry conditions can promote stomatal closure and alter the internal CO2/O2 balance.',
'C4 and CAM mechanisms help concentrate or conserve CO2 supply for productive fixation.'],[
('Conserve water','Stomata close under water stress.','Closure reduces water loss but limits gas exchange.'),('Change substrate competition','Lower CO2 relative to O2 increases the chance of RuBP oxygenation.','Rubisco can interact with either substrate.'),('Recover carbon at a cost','A multi-organelle pathway recovers some carbon while consuming energy and releasing CO2.','Recovery is less productive than direct CO2 fixation.')],
'Photorespiration is simply another name for ATP-producing respiration.','It is a distinct carbon-recovery pathway associated with Rubisco oxygenation and an energy cost.',[['Carboxylase route','Rubisco + CO2','Supports Calvin-cycle fixation'],['Oxygenase route','Rubisco + O2','Initiates photorespiration']])
Q('photorespiration',1,'Which enzyme can react with both CO2 and O2?', ['Rubisco','ATP synthase','Complex IV','Lactate dehydrogenase'],0,'Rubisco can catalyze RuBP carboxylation or oxygenation.')
Q('photorespiration',2,'Why can stomatal closure increase photorespiration?', ['It may lower internal CO2 relative to O2','It opens all thylakoid membranes','It replaces O2 with ATP','It directly makes glucose'],0,'Closure limits gas exchange and can reduce internal CO2, increasing competition from O2 at Rubisco.')
Q('photorespiration',3,'Which observation is most consistent with increased photorespiration?', ['Reduced net carbon gain despite ongoing light absorption','A new large ATP yield from Rubisco','No carbon loss under any conditions','Conversion of all leaf CO2 into oxygen'],0,'Photorespiration consumes resources and can release CO2, decreasing net productive carbon gain.')

L('c4cam','C4 & CAM: space versus time',10,7,'chloroplast','C4 and CAM pathways help improve CO2 availability for the Calvin cycle in challenging environments.','C4 separates initial fixation and the Calvin cycle across cell types; CAM separates them across times of day.','These mechanisms can reduce photorespiration or water loss, but they have energetic and ecological tradeoffs.','PEP carboxylase, four-carbon acids, Rubisco and specialized cells or storage patterns.','C4 plants deliver concentrated CO2 to bundle-sheath cells. CAM plants capture CO2 at night into organic acids, then release it for daytime Calvin-cycle activity.',[
'C4: initial fixation typically occurs in mesophyll cells; CO2 is supplied to the Calvin cycle in bundle-sheath cells.',
'CAM: stomata typically open at night; stored organic acids provide CO2 during daytime closure.',
'Both still use the Calvin cycle; they do not replace it with a completely separate sugar-making pathway.',
'The advantage depends on conditions; neither mechanism is universally best.'],[
('Capture CO2 initially','PEP carboxylase helps incorporate CO2 into four-carbon products.','This supports efficient initial CO2 capture.'),('Separate in space or time','C4 uses different cell types; CAM uses different times of day.','Different forms of separation fit different constraints.'),('Supply the Calvin cycle','CO2 is released near Rubisco for productive fixation.','The Calvin cycle remains the downstream carbon-building pathway.')],
'C4 and CAM are two names for the same separation mechanism.','C4 primarily separates processes in space; CAM primarily separates them in time.',[['C4','Mesophyll ↔ bundle sheath','Spatial separation'],['CAM','Night ↔ day','Temporal separation']])
Q('c4cam',1,'Which mechanism primarily separates CO2 capture and the Calvin cycle in time?', ['C4','CAM','Aerobic respiration','Glycolysis'],1,'CAM captures CO2 mainly at night and releases stored CO2 for daytime Calvin-cycle activity.')
Q('c4cam',2,'Which statement correctly describes C4 plants?', ['Initial fixation and the Calvin cycle are separated across cell types','The Calvin cycle is absent','Stomata must be open only at night','Rubisco directly replaces ATP synthase'],0,'C4 metabolism typically separates initial fixation in mesophyll cells from Calvin-cycle activity in bundle-sheath cells.')
Q('c4cam',3,'Why are C4 and CAM not universally superior to C3 photosynthesis?', ['Their benefits depend on environmental conditions and energetic tradeoffs','They never fix CO2','They produce no sugars','They only work without light'],0,'Benefits in heat or water limitation must be weighed against energetic costs and other environmental conditions.')

L('comparison','Compare the two energy systems',10,8,'light-reactions','Respiration and photosynthesis share electron transport and chemiosmosis, but their donors, acceptors and carbon roles differ.','Respiratory inner membranes and photosynthetic thylakoid membranes.','Comparison helps distinguish a shared mechanism from pathway-specific chemistry.','Respiration: NADH/FAD-linked electrons and O2. Photosynthesis: water, light and NADP+ in linear flow.','Both use electron transfer to support a proton gradient. ATP synthase uses proton return, but carbon oxidation and carbon fixation have different roles.',[
'Respiration generally oxidizes organic carbon; photosynthesis fixes inorganic carbon using energy captured from light.',
'In respiration, O2 is consumed as the terminal electron acceptor. In oxygenic photosynthesis, O2 is released from water.',
'Mitochondrial H+ accumulates in the intermembrane space; chloroplast H+ accumulates in the thylakoid lumen.',
'Plants perform both pathways. Net gas exchange combines photosynthesis and respiration rather than proving only one occurs.'],[
('Identify donor and acceptor','Name the electron source and final acceptor for each pathway.','Similar-looking membranes do not imply identical chemistry.'),('Locate the gradient','Find the high-H+ compartment and the direction of return.','Compartment names prevent directional confusion.'),('Connect energy and carbon','Compare fuel oxidation with carbon fixation.','The systems connect but are not simple reverse versions of every molecular step.')],
'Photosynthesis is cellular respiration run backward step by step.','Their overall carbon and gas relationships connect, but the pathways use different enzymes and mechanisms.',[['Respiration','NADH/FAD-linked donors → O2','ATP; high H+ in intermembrane space'],['Linear photosynthesis','H2O donor → NADP+','ATP and NADPH; high H+ in lumen']])
Q('comparison',1,'Which mechanism is shared by respiration and photosynthesis?', ['Chemiosmosis','Only lactate fermentation','Identical final electron acceptors','Absence of membranes'],0,'Both can use a proton gradient and ATP synthase, though electron donors and acceptors differ.')
Q('comparison',2,'Which pairing correctly identifies the high-proton compartments?', ['Respiration: matrix; photosynthesis: stroma','Respiration: intermembrane space; photosynthesis: lumen','Respiration: lumen; photosynthesis: cytosol','Both: cytosol'],1,'Protons accumulate in the mitochondrial intermembrane space and thylakoid lumen, then return through ATP synthase.')
Q('comparison',3,'A leaf releases net O2 in bright light. What can you conclude?', ['Gross photosynthetic O2 production exceeds respiratory O2 consumption under those conditions','Mitochondrial respiration has necessarily stopped','O2 was produced from CO2','Every cell in the leaf has identical gas exchange'],0,'Net exchange is a balance of processes. Positive net O2 release does not show that respiration is absent.')

L('experiments','Read evidence, not just a diagram',10,8,'chloroplast','Experiments test explanations by comparing controlled conditions and identifying what measurements can support.','A leaf-disc assay, isolated organelles or a respirometer can investigate aspects of energy metabolism.','A visual model proposes a mechanism; measured evidence is needed to evaluate it.','Independent variable, dependent measurement, controls, replicates and alternative explanations.','Vary one defined condition, keep relevant conditions comparable, record repeated measurements, and interpret the measurement without claiming more than it demonstrates.',[
'In a leaf-disc assay, flotation can reflect accumulated gas, but infiltration, density and other conditions affect results.',
'Dissolved-O2 changes reflect net production or consumption under the experimental conditions.',
'Controls help distinguish a treatment effect from background changes; biological replicates assess variation.',
'A model is a simplification. An unexpected result may reveal a missing variable rather than validate or invalidate every part of a pathway.'],[
('Define a testable question','Specify the treatment and measurement before collecting data.','A precise prediction makes evidence interpretable.'),('Control and replicate','Include an appropriate comparison and repeat independent samples.','Controls and replication address different sources of uncertainty.'),('Interpret limits','Relate results to the measured outcome and consider competing causes.','A correlation or model demonstration alone does not establish all causal details.')],
'One successful animation proves that the biological mechanism is correct.','An animation illustrates a proposal. Experiments and independent evidence are needed to test mechanisms.',[['Treatment','One defined manipulated condition','Independent variable'],['Measurement','Recorded response','Dependent variable'],['Interpretation','Evidence plus limitations','Avoid claiming an unmeasured result']])
Q('experiments',1,'Which is the dependent variable in a test of light intensity and net O2 production?', ['Measured change in O2','Lamp setting','The hypothesis','The control label'],0,'The dependent variable is the measured response. Light intensity is the manipulated independent variable.')
Q('experiments',2,'Why include biological replicates?', ['To assess variation between independent samples','To guarantee the desired result','To remove the need for controls','To turn a diagram into a measurement'],0,'Replicates characterize variability. They do not replace controls or guarantee a particular outcome.')
Q('experiments',3,'In a light-versus-dark test, O2 rises only in light. Which interpretation is most defensible?', ['Net O2 balance differs between these tested conditions','All light wavelengths have identical effects','Every pathway in every species is proven','The dark sample has no living cells'],0,'The result supports a condition-dependent difference in net O2 balance. It does not establish untested claims about wavelengths or all organisms.')

glossary={
'ATP':{'definition':'Adenosine triphosphate: a molecule whose hydrolysis can be coupled to cellular work.','lesson':'energy'},
'ADP':{'definition':'Adenosine diphosphate; adding Pi with an energy input can regenerate ATP.','lesson':'energy'},
'Pi':{'definition':'Inorganic phosphate, a reactant in ATP formation from ADP.','lesson':'chemiosmosis'},
'NADH':{'definition':'The reduced form of NAD+, carrying electrons toward respiratory pathways.','lesson':'energy'},
'NADPH':{'definition':'A reduced electron carrier supplying reducing power to biosynthesis, including Calvin-cycle reactions.','lesson':'light'},
'FADH2':{'definition':'Reduced FAD; FAD-linked electrons can enter the respiratory chain at a different point from NADH.','lesson':'etc'},
'Glycolysis':{'definition':'Cytosolic glucose breakdown to two pyruvates, with net ATP and NADH capture.','lesson':'glycolysis'},
'Pyruvate':{'definition':'A three-carbon product of glycolysis, converted to acetyl-CoA in aerobic glucose oxidation.','lesson':'pyruvate'},
'Acetyl-CoA':{'definition':'A carrier of a two-carbon acetyl group entering the citric acid cycle.','lesson':'pyruvate'},
'Oxaloacetate':{'definition':'The four-carbon acceptor regenerated in the citric acid cycle.','lesson':'citric'},
'Matrix':{'definition':'The compartment enclosed by the mitochondrial inner membrane.','lesson':'etc'},
'Cristae':{'definition':'Folds of the mitochondrial inner membrane that increase membrane area.','lesson':'etc'},
'Intermembrane space':{'definition':'The space between mitochondrial outer and inner membranes; the respiratory high-proton side.','lesson':'etc'},
'Ubiquinone':{'definition':'Q: a mobile electron carrier within the mitochondrial inner membrane.','lesson':'etc'},
'Cytochrome c':{'definition':'A mobile respiratory electron carrier on the intermembrane-space side of the inner membrane.','lesson':'etc'},
'Chemiosmosis':{'definition':'Energy coupling through ion movement down an electrochemical gradient across a membrane.','lesson':'chemiosmosis'},
'ATP synthase':{'definition':'A membrane-associated enzyme coupling proton flow to ATP synthesis.','lesson':'chemiosmosis'},
'Fermentation':{'definition':'A pathway regenerating NAD+ by reducing organic molecules, sustaining glycolysis.','lesson':'fermentation'},
'Stroma':{'definition':'The chloroplast fluid region outside thylakoid lumen spaces; location of the Calvin cycle.','lesson':'chloroplast'},
'Thylakoid':{'definition':'An internal chloroplast membrane compartment containing light-reaction machinery.','lesson':'chloroplast'},
'Lumen':{'definition':'The space inside a thylakoid, where protons accumulate during light reactions.','lesson':'light'},
'Granum':{'definition':'A stack of thylakoid discs.','lesson':'chloroplast'},
'Rubisco':{'definition':'The enzyme catalyzing CO2 fixation to RuBP; it can also catalyze RuBP oxygenation.','lesson':'calvin'},
'RuBP':{'definition':'Ribulose bisphosphate, the five-carbon CO2 acceptor regenerated in the Calvin cycle.','lesson':'calvin'},
'G3P':{'definition':'Glyceraldehyde-3-phosphate, the three-carbon net product exported from the Calvin cycle.','lesson':'calvin'},
'Photorespiration':{'definition':'Carbon-recovery reactions following Rubisco oxygenation, with an energy cost and some carbon loss.','lesson':'photorespiration'},
'Substrate-level phosphorylation':{'definition':'Direct transfer of a phosphate from a phosphorylated substrate to ADP or GDP.','lesson':'glycolysis'},
'Oxidative phosphorylation':{'definition':'ATP production through respiratory electron transport and chemiosmosis.','lesson':'chemiosmosis'},
'Photophosphorylation':{'definition':'ATP production using a proton gradient associated with photosynthetic electron flow.','lesson':'light'},
'Action spectrum':{'definition':'A biological response plotted against light wavelength.','lesson':'pigments'}
}
DATA={'title':'Cellular Energetics','unit':'Unit 2 · The Cell','lessons':lessons,'questions':questions,'glossary':glossary,'sequenceActivities':[{'id':'respiration-route','title':'Rebuild the respiratory route','steps':['Glycolysis produces pyruvate','Pyruvate oxidation produces acetyl-CoA','The citric acid cycle loads carriers','The electron transport chain builds a gradient','Protons return through ATP synthase'],'explanation':'The route links carbon oxidation to carrier reduction, electron transfer, a proton gradient and ATP synthesis. It is an overview, not a claim that every reaction starts only after the previous stage finishes.'},{'id':'calvin-route','title':'Rebuild the Calvin cycle','steps':['CO2 is fixed to RuBP','3-PGA intermediates are reduced','One net G3P can leave per three CO2','Most G3P carbon regenerates RuBP'],'explanation':'For three CO2, six G3P are generated in the reduction stage; one is the net export and five support RuBP regeneration.'}]}
(root/'data/curriculum.js').write_text('window.BIOVISION_DATA='+json.dumps(DATA,ensure_ascii=False,indent=2)+';\n',encoding='utf8')
(root/'data/curriculum.json').write_text(json.dumps(DATA,ensure_ascii=False,indent=2),encoding='utf8')
(root/'docs/CURRICULUM_CN.md').write_text('# BIOVISION 细胞能量单元\n\n按上传的 UI、HTML、访谈和 Campbell 第 9、10 章组织。课程与题目为本次新写的教学内容。\n\n共 '+str(len(lessons))+' 个微概念、'+str(len(questions))+' 道原创选择题及两项流程排序活动。\n\n'+ '\n'.join('## '+l['title']+'\n\n- 章节：'+str(l['chapter'])+'；建议用时：'+str(l['minutes'])+' 分钟。\n- 讲解采用 What / Where / Why / Who / How，附步骤说明、常见误解、输入输出表及三道练习。\n- 模型：'+l['model']+'。\n' for l in lessons)+'\n\n题库分为基础、应用、推理三级。自由回答采用自查提示，不假装自动人工智能评分。\n',encoding='utf8')
print('CONTENT_READY',len(lessons),'lessons',len(questions),'questions',len(glossary),'terms')
