const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const ROOT=process.env.BIOVISION_ROOT||path.resolve(__dirname,'..'),OUT=path.join(ROOT,'qa-output');fs.mkdirSync(OUT,{recursive:true});
const types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png','.mp4':'video/mp4','.pdf':'application/pdf','.json':'application/json','.md':'text/plain'};
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(req.url.split('?')[0]);const f=path.resolve(ROOT,'.'+(pathname==='/'?'/index.html':pathname));if(!f.startsWith(ROOT+path.sep)){res.writeHead(403);return res.end();}fs.readFile(f,(err,buf)=>{res.writeHead(err?404:200,{'Content-Type':types[path.extname(f)]||'application/octet-stream'});res.end(err?'Missing file':buf);});});
let browser;const checks=[],errors=[],external=[],failed=[],badStatus=[];
function check(label,condition){assert(condition,label);checks.push(label);console.log('PASS',label);}
async function route(p,hash){await p.evaluate(h=>location.hash=h,hash);await p.waitForTimeout(140);}
async function choice(p,correct=true){const n=await p.evaluate(ok=>{const L=window.BVLearn,q=L.questionById[L.state.session.queue[L.state.session.index]];return ok?q.answer:(q.answer+1)%4;},correct);await p.locator(`#session-answer input[value="${n}"]`).check();await p.locator('#session-answer button').click();}
(async()=>{
 await new Promise(resolve=>server.listen(4179,'127.0.0.1',resolve));
 browser=await chromium.launch({...(process.env.CHROME_EXECUTABLE?{executablePath:process.env.CHROME_EXECUTABLE}:{}),headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
 await context.route('**/*',r=>{const u=r.request().url();if(u.startsWith('http://127.0.0.1:4179/')||u.startsWith('file:')||u.startsWith('data:')||u.startsWith('blob:'))return r.continue();external.push(u);return r.abort();});
 const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('requestfailed',r=>{if(!r.failure()?.errorText?.includes('ERR_ABORTED'))failed.push(r.url());});p.on('response',r=>{if(r.status()>=400)badStatus.push([r.url(),r.status()]);});
 await p.goto('http://127.0.0.1:4179/');check('Home has actual 16-concept / 48-question unit',await p.locator('#home').innerText().then(t=>t.includes('0 / 16')&&t.includes('48')));
 const integrity=await p.evaluate(()=>{const D=BIOVISION_DATA,ids=new Set(D.lessons.map(l=>l.id));return D.lessons.length===16&&D.questions.length===48&&new Set(D.questions.map(q=>q.id)).size===48&&D.questions.every(q=>ids.has(q.lesson)&&q.options.length===4&&q.answer>=0&&q.answer<4&&q.explanation.length>30)&&D.lessons.every(l=>Object.keys(l.fiveW).length===5&&l.steps.length>=3&&D.questions.filter(q=>q.lesson===l.id).length===3);});check('Course/question data references and explanations are complete',integrity);
 await p.screenshot({path:path.join(OUT,'BIOVISION_Home_Desktop.png'),fullPage:true});
 const ids=await p.evaluate(()=>BIOVISION_DATA.lessons.map(l=>l.id));
 for(const id of ids){await route(p,'study/'+id);await p.locator('#study-model-view canvas').waitFor();assert.equal(await p.locator('#study form[data-quiz-question]').count(),3);assert.equal(await p.locator('#study .five-w button').count(),5);check('Lesson '+id+' loads with model, steps and three checks',await p.locator('#study-model-view canvas').evaluate(c=>c.toDataURL().length>9000));}
 await route(p,'study/etc');await p.locator('[data-action="five-w"][data-w="Where"]').click();check('Five-question selector updates actual compartment explanation',await p.locator('#five-w-text').innerText().then(t=>/inner membrane/i.test(t)));
 await p.locator('#five-w-text .keyword').first().click();check('Vocabulary popup shows a real definition',await p.locator('#term-dialog').isVisible()&&await p.locator('#term-definition').innerText().then(t=>t.length>20));await p.locator('[data-close="term-dialog"]').click();
 await p.locator('[data-prefix="study-model"][data-part="complex-ii"]').click();check('Selecting Complex II explains that it does not pump protons',await p.locator('#study-model-description').innerText().then(t=>/does not pump/i.test(t)));
 await p.locator('#study-model-xray').check();await p.locator('#study-model-cutaway').check();await p.locator('#study-model-isolate').check();await p.locator('[data-action="model-reset"][data-prefix="study-model"]').click();check('3D reset clears transparent, cutaway and isolate settings',await p.locator('#study-model-xray').isChecked()===false&&await p.locator('#study-model-cutaway').isChecked()===false&&await p.locator('#study-model-isolate').isChecked()===false);
 await p.locator('#study-model-view canvas').focus();await p.keyboard.press('ArrowRight');await p.keyboard.press('+');
 for(let i=0;i<4;i++){await p.locator(`[data-action="step"][data-index="${i}"]`).click();const v=await p.locator('#step-content video').evaluate(v=>({src:v.getAttribute('src'),duration:v.duration}));check('ETC step '+(i+1)+' links a supplied clip',v.src===`assets/videos/etc-step-${i+1}.mp4`);}
 await p.locator('details.lecture-slot summary').click();check('Supplied full ETC demo is a short playable clip',await p.locator('.lecture-slot video').evaluate(v=>v.readyState>=1&&v.duration>6&&v.duration<7));
 const note='Gradient links structure & function. <This is a note, not markup>.';await p.locator('#lesson-notes').fill(note);await p.waitForTimeout(450);await p.locator('[data-action="bookmark"]').click();await p.locator('#concept-tags summary').click();await p.locator('#custom-tag').fill('Review compartments');await p.locator('#tag-form button').click();await p.locator('[data-action="complete"]').click();check('Completion appears immediately in course directory',await p.locator('.concept-item.active .completion-mark').count()===1);
 const qid='etc-q1',wrong=await p.evaluate(id=>(BVLearn.questionById[id].answer+1)%4,qid);await p.locator(`form[data-quiz-question="${qid}"] input[value="${wrong}"]`).check();await p.locator(`form[data-quiz-question="${qid}"] button[type=submit]`).click();check('Incorrect mini-check shows explanation and enters review',await p.locator(`form[data-quiz-question="${qid}"] .incorrect`).count()===1&&await p.evaluate(id=>BVLearn.state.attempts[id].lastWrong,qid));
 await p.reload();check('Notes, tags, bookmarks and completion persist after reload',await p.locator('#lesson-notes').inputValue()===note&&await p.evaluate(()=>BVLearn.state.tags.etc.includes('Review compartments')&&BVLearn.state.bookmarks.includes('etc')&&BVLearn.state.completed.includes('etc')));
 await route(p,'gallery/mistakes');check('Mistake collection contains the incorrect question',await p.locator(`#gallery form[data-quiz-question="${qid}"]`).count()===1);
 const right=await p.evaluate(id=>BVLearn.questionById[id].answer,qid);await p.locator(`#gallery form[data-quiz-question="${qid}"] input[value="${right}"]`).check();await p.locator(`#gallery form[data-quiz-question="${qid}"] button[type=submit]`).click();check('Correct review removes wrong flag and schedules future review',await p.evaluate(id=>!BVLearn.state.attempts[id].lastWrong&&BVLearn.state.attempts[id].due>Date.now(),qid));await route(p,'home');await route(p,'gallery/mistakes');check('Answered-correctly item leaves due review until scheduled',await p.locator(`#gallery form[data-quiz-question="${qid}"]`).count()===0);
 await p.evaluate(id=>{BVLearn.state.attempts[id].due=Date.now()-1;BVLearn.save();},qid);await route(p,'gallery/saved');await route(p,'gallery/mistakes');check('Scheduled review becomes available at its due time',await p.locator(`#gallery form[data-quiz-question="${qid}"]`).count()===1);
 await p.locator('#search-input').fill('Calvin');await p.locator('#search-form button').click();check('Universal Finder links matching concepts',await p.locator('#search-results a[href="#study/calvin"]').count()>0);await p.locator('#search-results a[href="#study/calvin"]').first().click();await p.waitForFunction(()=>document.querySelector('#study .concept-heading h2')?.textContent.includes('Calvin'));check('Search result opens the requested concept',await p.locator('#study .concept-heading h2').innerText().then(t=>/Calvin/.test(t)));
 await route(p,'gallery');for(const id of ['mitochondrion','chloroplast','respiratory-etc','light-reactions']){await p.locator(`#gallery [data-action="open-model"][data-model="${id}"]`).click();await p.locator('#modal-model-view canvas').waitFor();check('Gallery model '+id+' opens with source download',await p.locator(`#model-dialog a[href="assets/models/${id}.blend"]`).count()===1);await p.locator('[data-close="model-dialog"]').click();}
 await route(p,'exam');await p.locator('#exam-scope').selectOption('etc');check('Concept scope clamps session to three questions',await p.locator('#exam-count').inputValue()==='3');await p.locator('#exam-level').selectOption('2');check('Selected difficulty clamps to available question',await p.locator('#exam-count').inputValue()==='1');await p.locator('#exam-form button[type=submit]').click();await choice(p,true);await p.locator('[data-action="next-question"]').click();check('Practice scores the chosen question correctly',await p.locator('.result-summary h2').innerText()==='1 / 1');
 await p.locator('[data-action="new-session"]').click();await p.locator('#exam-mode').selectOption('adaptive');await p.locator('#exam-level').selectOption('1');await p.locator('#exam-count').fill('5');await p.locator('#exam-time').selectOption('5');await p.locator('#exam-form button[type=submit]').click();
 await choice(p,true);await p.locator('[data-action="next-question"]').click();await choice(p,true);await p.locator('[data-action="next-question"]').click();check('Adaptive mode raises level after two correct answers',await p.evaluate(()=>BVLearn.questionById[BVLearn.state.session.queue[BVLearn.state.session.index]].level===2));await choice(p,false);await p.locator('[data-action="next-question"]').click();check('Adaptive mode lowers level after an incorrect response',await p.evaluate(()=>BVLearn.state.session.currentLevel===1));
 const resumable=await p.evaluate(()=>({id:BVLearn.state.session.id,index:BVLearn.state.session.index,answers:Object.keys(BVLearn.state.session.answers).length}));await p.reload();check('Unfinished session resumes after refresh',await p.evaluate(s=>BVLearn.state.session.id===s.id&&BVLearn.state.session.index===s.index&&Object.keys(BVLearn.state.session.answers).length===s.answers,resumable));
 await p.evaluate(()=>{BVLearn.state.session.deadline=Date.now()-1;BVLearn.save();});await p.waitForTimeout(1200);check('Timer expires and records unanswered questions',await p.locator('.result-summary h2').innerText()==='2 / 5'&&await p.locator('.result-summary').innerText().then(t=>t.includes('3 answered · 2 unanswered')));
 const engine=await p.evaluate(()=>{const L=BVLearn,base=L.fresh(),q=L.questionById['etc-q1'];let ok=true;const bads=[{queue:[],index:0},{queue:['etc-q1'],index:1},{queue:['etc-q1'],index:0,mode:'untrusted'},{queue:['etc-q1','etc-q1'],index:0},{queue:['no-such-question'],index:0}];for(const change of bads){const s={id:'x',mode:'practice',scope:'etc',level:'mixed',queue:['etc-q1'],answers:{},index:0,targetCount:3,...change};ok=ok&&L.validate({...base,session:s}).session===null;}const good=L.validate({...base,session:{id:'ok',mode:'practice',scope:'etc',level:'mixed',queue:['etc-q1'],answers:{'etc-q1':{choice:q.answer,correct:false},'calvin-q1':{choice:0}},index:0,targetCount:3}});return ok&&good.session.answers['etc-q1'].correct===true&&!good.session.answers['calvin-q1'];});check('Progress import discards malformed sessions and recomputes correct answers',engine);
 await route(p,'mybio');const downloadPromise=p.waitForEvent('download');await p.locator('[data-action="export-progress"]').click();const downloaded=await downloadPromise;const backup=JSON.parse(fs.readFileSync(await downloaded.path(),'utf8'));check('Progress export downloads real notes, questions and history',backup.notes.etc===note&&backup.history.length===2);
 await p.locator('#rename').fill('Different name');await p.locator('#rename-form button').click();await p.locator('#import-progress').setInputFiles({name:'progress.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await p.waitForTimeout(200);check('Progress backup import restores profile and notes',await p.locator('#rename').inputValue()==='Learner'&&await p.evaluate(()=>BVLearn.state.notes.etc!==undefined));
 await p.locator('#import-progress').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"version":999}')});await p.waitForTimeout(150);check('Invalid backup shows an error without destroying progress',await p.evaluate(()=>BVLearn.state.notes.etc!==undefined)&&await p.locator('#toast').innerText().then(t=>t.includes('version 1')));
 await route(p,'forum/etc');const payload='<img src=x onerror="window.BAD=true"> Why does the gradient matter?';await p.locator('#discussion-text').fill(payload);await p.locator('#discussion-form button').click();check('Discussion draft stays local and renders as text',await p.locator('.discussion-item p').innerText()===payload&&await p.locator('.discussion-item img').count()===0&&await p.evaluate(()=>!window.BAD));
 await route(p,'gallery/craft');await p.locator('[data-action="check-sequence"]').first().click();check('Sequence activity recognizes an incorrect ordering',await p.locator('#sequence-feedback-respiration-route .incorrect').count()===1);for(let i=4;i>0;i--)await p.locator(`[data-action="move-sequence"][data-game="respiration-route"][data-position="${i}"][data-direction="-1"]`).click();await p.locator('[data-action="check-sequence"][data-game="respiration-route"]').click();check('Sequence movement and correct-order feedback work',await p.locator('#sequence-feedback-respiration-route .correct').count()===1);
 // Inspect all runtime links, and both desktop/mobile layouts across six primary pages and gallery tabs.
 const paths=new Set();for(const width of [1440,390,320]){await p.setViewportSize({width,height:900});for(const hash of ['home','study/etc','study/calvin','gallery/resources','gallery/graph','gallery/craft','gallery/saved','gallery/mistakes','exam','forum','mybio']){await route(p,hash);check('No horizontal page overflow '+width+'px / '+hash,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));for(const url of await p.locator('a[href],img[src],video[src],script[src],link[href]').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('href')||n.getAttribute('src')).filter(v=>v&&!v.startsWith('#')&&!/^(https?:|blob:|data:)/.test(v))))paths.add(url);}}
 for(const rel of paths)check('Runtime asset exists: '+rel,fs.existsSync(path.resolve(ROOT,rel)));
 await p.setViewportSize({width:1440,height:1000});await route(p,'study/etc');await p.locator('#study-model-view').screenshot({path:path.join(OUT,'BIOVISION_ETC_Model.png')});await p.screenshot({path:path.join(OUT,'BIOVISION_Study_Desktop.png'),fullPage:true});await route(p,'exam');await p.screenshot({path:path.join(OUT,'BIOVISION_Quiz_Desktop.png'),fullPage:true});await p.setViewportSize({width:390,height:844});await route(p,'study/etc');await p.screenshot({path:path.join(OUT,'BIOVISION_Study_Mobile.png'),fullPage:true});
 // Local file URL test with all internet requests blocked.
 const filePage=await context.newPage();filePage.on('pageerror',e=>errors.push(e.message));await filePage.goto('file://'+ROOT+'/index.html#study/chloroplast');await filePage.locator('#study-model-view canvas').waitFor();check('Direct local-file opening renders complete course and 3D',await filePage.locator('#study .concept-heading h2').innerText().then(t=>/Chloroplast/.test(t))&&await filePage.locator('#study-model-view canvas').evaluate(c=>c.toDataURL().length>9000));await route(filePage,'exam');await filePage.locator('#exam-count').fill('1');await filePage.locator('#exam-form button[type=submit]').click();await choice(filePage,true);await filePage.locator('[data-action="next-question"]').click();check('Quiz works directly from file:// with no server',await filePage.locator('.result-summary h2').innerText()==='1 / 1');
 check('No uncaught browser errors',errors.length===0);check('No external runtime requests',external.length===0);check('No missing runtime assets or failed requests',badStatus.length===0&&failed.length===0);
 const report={date:'2026-10-06',browser:await browser.version(),checks:checks.length,passed:checks,errors,externalRequests:external,failedRequests:failed,badStatus,viewports:[1440,390,320],directFileTest:true};fs.writeFileSync(path.join(OUT,'qa-results.json'),JSON.stringify(report,null,2));console.log('COMPLETE',checks.length,'checks');
})().catch(e=>{console.error('FAIL',e);fs.writeFileSync(path.join(OUT,'qa-failure.json'),JSON.stringify({passed:checks,errors,external,failed,badStatus,error:String(e)},null,2));process.exitCode=1;}).finally(async()=>{await browser?.close();await new Promise(resolve=>server.close(resolve));});
